- name: Configuring Docker
  hosts: localhost
  tasks:
          - name: configuring docker repository
            yum_repository:
                    name: docker
                    description: docker
                    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                    gpgcheck: no


          - name: installing docker-ce
            command: yum install docker-ce --nobest -y

          - name: installing python3
            yum:
                    name: python36
                    state: present

          - name: starting and enabling docker services
            service:
                    name: docker
                    state: started
                    enabled: yes

          - name: downloading docker python files
            pip:
                    name: docker

          - name: creating directory mydoc
            file:
                    name: mydoc
                    state: directory

          - name: copy html files
            copy:
                    src: index.html
                    dest: /mydoc/

          - name: starting httpd webserver using Docker
            docker_container:
                            name: webserver
                            image: httpd
                            # image: sankeerthbussa/centos_ssh:version1
                            state: started
                            exposed_ports:
                                    - 80
                            volumes:
                                    - /mydoc/:/usr/local/apache2/htdocs/
                                    # - /mydoc:/var/www/html/
          - name: getting container info
            community.docker.docker_container_info:
                    name: webserver
            register: c

          - name: updating inventory
            blockinfile:
                    path: /root/docker-ansible/inventory 
                    block: |
                            [docker_IPs]
                            {{ c.container.NetworkSettings.IPAddress }}
